### PR TITLE
automatic reset of loads 

### PR DESCRIPTION
**Pull request by evlas**
Hi,
I propose an automatic reset of the loads.
Would you be interested in it?

### CODE REVIEW

**Comment by legolas0802** [comment]
Hi, it might also be interesting. But keeping the switches off is a deliberate thing, since modern appliances consume energy even when turned off.

**Comment by evlas** [comment]
Hi, I never understood your statement, if something is ON I need it ON and I can leave it OFF by inserting it among the exceptions.

Anyway yours is a good job and the owner is always right, I will try to keep an alternate version.
thanks for your efforts.

**Comment by legolas0802** [comment]
from what I understand giving a quick read of the code.  your version works with switches always on.  or did I miss something?

**Comment by evlas** [comment]
the switches are turned OFF when I am away from home and turned ON when I am at home, with scenes.
I have threshold crossings only when I am at home, I have only electric devices.
The device that exceeds the threshold is usually the heat pump that is always on because it makes water heater and heating / cooling

**Pull request closed without merging**
